version: "3.9"

services:
  backend_ai:
    build:
      context: ./backend_ai
    container_name: backend_ai
    ports:
      - "8000:8000"
    volumes:
      - ./backend_ai:/app
    restart: always

  frontend_user:
    build:
      context: ./frontend_user
    container_name: frontend_user
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_user:/app
    depends_on:
      - backend_ai
    restart: always
